# Generated by Django 4.1.6 on 2023-04-26 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserReg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=250)),
                ('password1', models.CharField(blank=True, max_length=250)),
                ('password2', models.CharField(blank=True, max_length=250)),
                ('location', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phonenumber', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.PositiveIntegerField()),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, default=None, upload_to='vehicle/uploads')),
                ('image1', models.ImageField(blank=True, default=None, upload_to='vehicle/uploads')),
                ('image2', models.ImageField(blank=True, default=None, upload_to='vehicle/uploads')),
                ('image3', models.ImageField(blank=True, default=None, upload_to='vehicle/uploads')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used.userreg')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateordered', models.DateField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='used.userreg')),
                ('vehicleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distinctve', to='used.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Favourites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Addtocart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='used.vehicle')),
            ],
        ),
    ]
