# Generated by Django 4.2 on 2023-05-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0002_favourites_userid_alter_userreg_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandname', models.CharField(max_length=250, null=True)),
                ('model', models.CharField(blank=True, max_length=250, null=True)),
                ('sprice', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elocation', models.CharField(max_length=250, null=True)),
                ('semail', models.CharField(max_length=250, null=True)),
                ('sphonenumber', models.CharField(max_length=225, null=True)),
                ('vimages', models.ImageField(blank=True, default=None, upload_to='vehicle/uploads')),
            ],
        ),
    ]
