# Generated by Django 4.2 on 2023-05-04 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0003_sellervehicle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellervehicle',
            name='approvals',
            field=models.CharField(choices=[('Approval', 'Approval'), ('Not approval', 'Not approval')], default='N', max_length=300, null=True),
        ),
    ]
