# Generated by Django 4.2 on 2023-05-04 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0004_sellervehicle_approvals'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='used.userreg'),
            preserve_default=False,
        ),
    ]
