# Generated by Django 4.2 on 2023-05-08 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0005_vehicle_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='userid',
        ),
    ]
