# Generated by Django 4.2 on 2023-05-08 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0007_vehicledetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vbrand',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vimage',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vimage1',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vimage2',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vimage3',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vmileage',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vmodel',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vprice',
        ),
        migrations.RemoveField(
            model_name='vehicledetails',
            name='vyear',
        ),
        migrations.AddField(
            model_name='vehicledetails',
            name='vvehicleid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vvehicleid', to='used.vehicle'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vehicledetails',
            name='vuserid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuserid', to='used.userreg'),
        ),
    ]
