# Generated by Django 4.2 on 2023-05-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0008_remove_vehicledetails_vbrand_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourites',
            name='userid',
        ),
    ]
