# Generated by Django 4.2 on 2023-05-08 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('used', '0009_remove_favourites_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourites',
            name='userid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='used.userreg'),
            preserve_default=False,
        ),
    ]
