from django.urls import path
from .import views
urlpatterns=[
    path('',views.home,name='home'),
    path('login/',views.login,name='login'),
    path('about/',views.about, name='about'),
    path('register/',views.register,name='register'),
    path('userchk',views.userchk,name='userchk'),
    path('delete/',views.delete,name='delete'),
    path('userdisplay/',views.userdisplay,name='userdisplay'),
    path('vehicledisplay/',views.vehicledisplay,name='vehicledisplay'),
    path('savedata/',views.savedata,name='savedata'),
    #path('add_product,views.add_product,name='add_product'),
    path('checkout/',views.checkout,name='checkout'),
    path('productcard/',views.productcard,name='productcard'),
    path('vehicle_list/',views.vehicle_list,name='vehicle_list'),
    path('base/',views.base,name='base'),
    path('userpage1/',views.userpage1, name='userpage1'),
    path('user_profile/',views.user_profile, name='user_profile'),
    path('logout/', views.logout_view, name='logout_view'),
    # path('product_wishlist/', views.product_wishlist, name='product_wishlist'),
    path('vehicle_detail/', views.vehicle_detail, name='vehicle_detail'),
    path('buy_vehicle/<int:pk>/', views.buy_vehicle, name='buy_vehicle'),
    # path('add_to_wishlist/<int:pk>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('user_profile', views.user_profile, name='user_profile'),
    path('demo_update_view/', views.demo_update_view, name='demo_update_view'),
    path('seller/', views.seller, name='seller'),
    path('sellersad/', views.sellersad, name='sellersad'),
    path('add_to_wishlist/', views.add_to_wishlist, name='add_to_wishlist'),
    path('wishlist_demo_page/', views.wishlist_demo_page , name='wishlist_demo_page'),
    path('approval/', views.approval , name='approval'),
    path('wishlist_view/', views.wishlist_view , name='wishlist_view'),
    # path('wishlist/', views.wishlist , name='wishlist'),
    # path('object_detection/', views.object_detection, name='object_detection'),
    path('lastpage/', views.lastpage , name='lastpage'),
    path('vehicledetailsave/',views.vehicledetailsave,name='vehicledetailsave'),
]

